language: node_js
node_js:
  - stable
before_script:
- wget http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d
/home/travis/virtualenv/python2.7.12/bin/
- export CHROME_BIN=chromium-browser
script:
  - node test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist