sudo: required
language: node_js
node_js:
  - stable
  before_script:
    - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
    - export CHROME_BIN=chromium-browser
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - pip install selenium==2.48.0
script:
  - node test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist